### ISSUE TITLE
Error while executing "make"

### ISSUE THREAD

**Issue by E-Mans-Application** [HaarigerHarald/omxiv#17] opened 2019-02-09 15:16 UTC
Hello,

I'm trying to install omxiv on my Raspberry Pi 3.
I cloned with git then I ran `make ilclient` successfully.
https://pastebin.com/n0yB6iCG

But when I run the command "make", I got the error:
```
Makefile.include:11: recipe for target 'omx_render.o' failed
make: *** [omx_render.o] Error 1
```
Running with sudo does not solve the issue.
https://pastebin.com/nBH9MHVx
https://pastebin.com/RDdpVFm5

**Comment by Favrito** [comment] 2019-02-10 01:09
I have this same problem, please someone help!

**Comment by HaarigerHarald** [comment] 2019-02-10 13:30
Duplicate of #12 and #14

**Comment by E-Mans-Application** [comment] 2019-02-10 13:58
I have already run "apt-get upgrade" (took almost an hour)
I'm trying another update then I'll tell you if this is working fine.

**Comment by nagualcode** [comment] 2019-02-10 14:04
"Building
You will **need the development header for libjpeg and libpng (Debian: libjpeg8-dev, libpng12-dev).** Then build it on the Pi with:

**make ilclient**
**make**
And install with:

sudo make install"

**Comment by E-Mans-Application** [comment] 2019-02-10 14:35
I had already installed libjpeg and libpng.
After running : `sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade && sudo rpi-update && sudo reboot`, the installation of omxiv worked. I think "rpi-update" made the difference.

**Comment by jackdaniels92** [comment] 2019-02-21 14:32
> I had already installed libjpeg and libpng.
> After running : `sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade && sudo rpi-update && sudo reboot`, the installation of omxiv worked. I think "rpi-update" made the difference.

Thats correct. "rpm-update" made the difference. Thanks a lot.

**Comment by bitstreamreport** [comment] 2019-02-21 14:37
It is important to notice that this is a raspbian distro issue, not omxiv.
Raspbian seems to have a conservative way to update the firmware libs, and this "rpi-update" tool, forces the update to the lastest version. With other distros, the libs can be already updated.

**Comment by rebroad** [comment] 2019-09-11 16:56
is it possible to get this working without needing to do an rpi-update?

**Comment by nagualcode** [comment] 2019-09-11 18:18
> is it possible to get this working without needing to do an rpi-update?

It is important to notice that this is a raspbian distro issue, not omxiv.
Raspbian seems to have a conservative way to update the firmware libs, and this "rpi-update" tool, forces the update to the lastest version. With other distros, the libs can be already updated.

**Comment by Ruffio** [comment] 2020-08-26 14:15
Can this issue be closed?

**Closed as completed** 2020-09-20 19:17 UTC
